CREATE TABLE GRILOS (
   GRILO_NOME VARCHAR(30),
   GRILO_ID INTEGER,

   CONSTRAINT GRI_PK PRIMARY KEY (GRILO_ID)
);

CREATE TABLE CIGARRAS (
   CIGARRA_NOME VARCHAR(30),
   CIGARRA_ID INTEGER,

   CONSTRAINT CIG_PK PRIMARY KEY (CIGARRA_ID)
);